# -*- coding: utf-8 -*-
"""EE604-Assignment-1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jn7khdOH38y7U4iYnCh3yMnX7kbgrOQ8
"""

import cv2
import numpy as np

"""### Draw a circle"""

def dist(p1,p2):
  return np.sqrt((p1[0]-p2[0])**2 + (p2[1]-p1[1])**2)

def circle(img,a,b):
  for i in range(a-26,a+26):
    for j in range(b-26,b+26):
      if dist([i,j],[a,b])<=25:
        img[j][i]=255
  return img

"""### Main code"""

Img = np.zeros((300, 500), np.uint8)

# coordinates where circle are to be formed for each number

dot0 = np.array([[1,1,1],[1,0,1],[1,0,1],[1,0,1],[1,1,1]])
dot1 = np.array([[0,1,0],[1,1,0],[0,1,0],[0,1,0],[1,1,1]])
dot2 = np.array([[1,1,1],[0,0,1],[1,1,1],[1,0,0],[1,1,1]])
dot3 = np.array([[1,1,1],[0,0,1],[1,1,1],[0,0,1],[1,1,1]])
dot4 = np.array([[1,0,0],[1,0,1],[1,1,1],[0,0,1],[0,0,1]])
dot5 = np.array([[1,1,1],[1,0,0],[1,1,1],[0,0,1],[1,1,1]])
dot6 = np.array([[1,1,1],[1,0,0],[1,1,1],[1,0,1],[1,1,1]])
dot7 = np.array([[1,1,1],[0,0,1],[0,0,1],[0,0,1],[0,0,1]])
dot8 = np.array([[1,1,1],[1,0,1],[1,1,1],[1,0,1],[1,1,1]])
dot9 = np.array([[1,1,1],[1,0,1],[1,1,1],[0,0,1],[1,1,1]])

dict = {'0':dot0, '1':dot1, '2':dot2, '3':dot3, '4':dot4, '5':dot5, '6':dot6, '7':dot7, '8':dot8, '9':dot9}

num = input("Enter any number between 0 and 99: ")


# To handle the case when sigle digit is entered

if(len(num)==1):
  num = '0'+num

a = 0
b = 0

for i in range(70,200,55):
  for j in range(40,270,55):
    if dict[num[0]][a,b]==1:
      image = circle(Img,i,j)
    a+=1
  b+=1
  a=0

a = 0
b = 0

for i in range(300,450,55):
  for j in range(40,270,55):
    if dict[num[1]][a,b]==1:
      image = circle(Img,i,j)
    a+=1
  b+=1
  a=0

# # Displaying the image
# cv2_imshow(image)
cv2.imwrite("dotmatrix.jpg", image)